### PR TITLE
Fix minor typo

### PR DESCRIPTION
**Pull request by rendall**
It's such a minor typo, I would not be offended if you rejected this PR and included the change in another more substantial PR so as not to clutter your repo history

### CODE REVIEW

**Comment by thoppe** [comment]
Minor as it may be, I did author this bot once:

https://github.com/thoppe/orthographic-pedant

Sooooooo... I'm happy to accept any positive change!

**Comment by rendall** [comment]
> Minor as it may be, I did author this bot once:
> 
> https://github.com/thoppe/orthographic-pedant

It reminds me of the late, lamented, genius Twitter-bot [Stealth Mountain](https://twitter.com/StealthMountain) (account suspended). I miss that bot!

<https://slate.com/culture/2012/01/stealth-mountain-the-twitter-bot-devoted-to-a-single-grammatical-error.html>

**Comment by thoppe** [comment]
Agreed! That bot was one of the good ones (and an inspiration to my hipster pendant). Out of curiosity, was your PR driver by Hacktoberfest? I've had three PRs to this repo recently -- it was designed as an art project and less of a working library!

**Comment by rendall** [comment]
> Out of curiosity, was your PR driver by Hacktoberfest? I've had three PRs to this repo recently -- it was designed as an art project and less of a working library!

Your project hit the front page of [Hacker News](https://news.ycombinator.com/item?id=28691005) recently.  I got here from there.

**Comment by thoppe** [comment]
That makes sense! Thanks for the info.

**Pull request merged**
